### ISSUE TITLE
Issue with the completed functionality

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/todo-app#12]
As you see when multiple todos are marked completed if I delete a completed task, then every other completed task turns incomplete.
https://user-images.githubusercontent.com/54741119/135874899-d9b99a15-4295-4bd4-8e48-c2334cad321c.mp4

**Comment by nirajacharyaa** [comment]
feel free to work by yourself leaving a reply only mentioning me, no need to wait for the assignment.

**Comment by MuhammadTanveer94** [comment]
@nirajacharyaa could you please assign me this?

**Comment by nirajacharyaa** [comment]
@MuhammadTanveer94 I said no need to ask for an assignment, you can work on your own.

**Comment by Aashishkushwaha** [comment]
Hi @nirajacharyaa , I'm working on resolving this issue.

**Comment by nirajacharyaa** [comment]
That's good first come first serve it is. Anyone who makes the first PR will get merged another one will get `hacktoberfest-accepted` label. Both will be counted in hacktoberfest.

**Comment by Aashishkushwaha** [comment]
Hi @nirajacharyaa, I've fixed the issue with the logic & raised the PR #23. Please review the PR & merge it. Thanks :)

**Comment by nirajacharyaa** [comment]
Keep contributing. Happy Hacktoberfest, don't forget to star the repo. Thank you.

**Comment by nirajacharyaa** [comment]
@MuhammadTanveer94 If you have written some fix to it don't worry I will give you PR hacktoberfest-accepted label.
