### ISSUE TITLE
it is not responsive

### ISSUE THREAD

**Issue by Mishthisinghal** [nirajacharyaa/todo-app#13]
Can i work on this issue?

**Comment by nirajacharyaa** [comment]
so me some screenshot instances of the issue and then you can work.

**Comment by Mishthisinghal** [comment]
it's not responsive for mobile :

![Screenshot_20211004_211427](https://user-images.githubusercontent.com/79502029/135882324-e531ee22-7ddc-46e3-a021-19b94b51f8ef.png)
