### ISSUE TITLE
ClearAll button

### ISSUE THREAD

**Issue by Mitushi-23** [nirajacharyaa/todo-app#15]
Clear all button can be added to delete all the items at a time. No need of deleting them individually.

**Comment by Mitushi-23** [comment]
@nirajacharyaa can I work on this issue?

**Comment by nirajacharyaa** [comment]
Yes do that, and check everything properly band fetch upstream before making a PR request.

**Comment by Mitushi-23** [comment]
@nirajacharyaa  Can you please include my contribution in hactoberfest?

**Comment by nirajacharyaa** [comment]
@Mitushi-23  this repo has hacktoberfest as a topic so every PR made to this repo is by default counted even without a label.
