### ISSUE TITLE
Change to responsive buttons

### ISSUE THREAD

**Issue by bhargav794** [nirajacharyaa/todo-app#16]
Here is a screenshot of how buttons are looking on smaller screen sizes. Please assign this issue to me I can fix this
![to do app ](https://user-images.githubusercontent.com/66371186/135951205-b3fb6d86-3fce-4248-b1a0-9babed59fb5b.png)

As you can see some buttons in the list are beside one another and others are below one another this kind of inconsistency might cause troubles for UX. Assign me this issue and I'll work on it
Thank you

**Comment by nirajacharyaa** [comment]
Go on.

**Comment by bhargav794** [comment]
Thanks
