### ISSUE TITLE
Wants to add some new features

### ISSUE THREAD

**Issue by juuuuuuun** [nirajacharyaa/todo-app#39]
Can I add some features below the lists?
~~-Display current time+weather(can utilize external api)~~
~~-Based on the time automatically change the dark-light mode~~
-Insert more animations to good effect
-Progressive bar to check easily how many tasks have been done and need to do

**Comment by nirajacharyaa** [comment]
Yes, go on.

**Comment by juuuuuuun** [comment]
Updated by #40

**Comment by juuuuuuun** [comment]
Closed by #40
