### ISSUE TITLE
Store the todo in localStorage.

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/todo-app#4]

**Comment by juuuuuuun** [comment]
Can work on this? :_)

**Comment by nirajacharyaa** [comment]
Yes, go on. @juuuuuuun

**Comment by juuuuuuun** [comment]
> Yes, go on. @juuuuuuun

Thank you!

**Comment by juuuuuuun** [comment]
Updated [d1d5380](https://github.com/nirajacharyaa/todo-app/pull/7/commits/d1d5380a2d19a1ada100f417fb0e1a7459f32f4d)
